### ISSUE TITLE
Pagination is not working when using with Postgres Database

### ISSUE THREAD

**Issue by rajhans84** [opensingular/singular-keycloak-database-federation#16]
Hi there, Thank you so much for such a great project. I am using this provider to connect PostgrSQL database with large user database. Found few issue in this but major one is that it fetches only 18 users from the pg database and the pagination to fetch more users doesn't work. Could you provide instructions to use search feature. Thanks

**Comment by viniciusuriel** [comment]
Hi there, you are right, there is currently no actual support to pagination. I will try to fix it as soon as possible.

**Comment by viniciusuriel** [comment]
Now you can view users at User listing on manage area with real pagination. Although the issue you pointed here did not prevent correct users authentication it is now fixed.
