### ISSUE TITLE
Keycloak 19 support

### ISSUE THREAD

**Issue by xsuchy09** [opensingular/singular-keycloak-database-federation#19]
Hi, first of all thanks for your work. It looks like Keycloak v19 is not supported. When I try to add new User Federation just unknown error is returned:
> User federation provider could not be created: unknown_error

Log (with many other messages):
> keycloak  | 2022-08-08T12:37:45.090310671Z 2022-08-08 12:37:45,089 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-27) Uncaught server error: java.lang.NullPointerException
> keycloak  | 2022-08-08T12:37:45.090348970Z     at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)

**Comment by viniciusuriel** [comment]
Hi there, after some research I found out that there is a bug in keycloak new admin theme. That bug prevents, keycloak admin interface from rendering configuration properties for any custom provider, including this one, of course. You can check this bug status on the following links:
- https://github.com/keycloak/keycloak/issues/18157
- https://github.com/keycloak/keycloak/issues/13753

Fortunately, there is a way to workaround it:
- Click "Realm Settings" on the left menu
- Then click the tab "Themes"
- And, for the selection input labeled "Admin console theme", select "keycloak"
- Force page refresh
- Now, if you try to configure this provider again, keycloak should render all configuration fields and everything else should work fine.
