### ISSUE TITLE
Keycloak 19.0.2 -  "User federation provider could not be created: unknown_error" when adding provider 

### ISSUE THREAD

**Issue by jongreene76** [opensingular/singular-keycloak-database-federation#25]
When attempting to add a provider using this SPI in version 19.0.2 Keycloak shows "User federation provider could not be created: unknown_error"

**Comment by jongreene76** [comment]
If you switch the Master realm Theme from "Keycloak.v2" to the original "Keycloak" theme the error no longer occurs.

**Comment by viniciusuriel** [comment]
This issue is a duplicate of #19 , the solution is exactly the one you figured out.
