### ISSUE TITLE
provider not working with keycloak 19.0.3

### ISSUE THREAD

**Issue by KDMRyanT** [opensingular/singular-keycloak-database-federation#26]
Hello,
Was working with keycloak 18 previously and this provider/extension was working perfect!  However, I have now switch my dev setup to keycloak 19.0.3 ( latest ) and have placed the jar packages in /opt/keycloak/providers under keycloak 19.0.3.  On running start-dev, I see under user federation the singular-keycloak-database-federation.  I go to try and setup 1 to either postgres or oracle and on placing the same parameters within it, on hitting save I get a "unknown_error" displayed from keycloak 19.0.3.

Is this provider/extension compatible with 19.0.3?  Should I be compiling the extension with keycloak 19.0.3 set in pom.xml ( out of the box/git pull keycloak version is set to 17.0.1

Please advise

**Comment by viniciusuriel** [comment]
Hello, have you checked if the problem you are facing is the same described in issues #19 and #25 ?

**Comment by KDMRyanT** [comment]
Hello, I have done this now and it is working under keycloak theme.  Thank you.  From what I have read on those issues - looks like this is solved with the nightly build of the theme?  Has anyone tested?

**Comment by viniciusuriel** [comment]
Hi, I am glad you manage to solve it. I have not tested it again, but I think I would rather wait for a new release with this bug fixed than using nightly releases.
