### ISSUE TITLE
Issue when saving user federation info

### ISSUE THREAD

**Issue by imaginae** [opensingular/singular-keycloak-database-federation#27]
Hi,

we have found issues with keycloak 19, once installed and working :

25 12:07:24,689 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('jdbc:jtds:sqlserver://server-name/database_name;instance=instance_name')
 at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 45] (through reference chain: org.keycloak.representations.idm.ComponentRepresentation["config"]->org.keycloak.common.util.MultivaluedHashMap["url"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)

It happens when saving information into Add singular-db-user-provider provider option.
Regards

**Comment by viniciusuriel** [comment]
Hi, have you checked the "Known issue" section in project README.md? There are a several reports already closed due to a Keycloak 19 default theme bug. For reference you could also see issues #19 , #24 , #25 and #26   and let me know if you manage to workaround the problem.

**Comment by imaginae** [comment]
Hi @viniciusuriel , 

yes, checked. It seems an issue with keycloak 2. 

So as per your suggestion, going to Realm Settings and configure keycloack theme, then do logout and login again and go to user federation works.

Thanks for your support!
