### ISSUE TITLE
Is federation via IBM DB2 possible?

### ISSUE THREAD

**Issue by CM4115** [opensingular/singular-keycloak-database-federation#32]
I tried adding the jdbc driver for db2, but in the federation setup it refuses to connect to the db.
I'm new and exploring thanks :))

**Comment by viniciusuriel** [comment]
HI @CM4115 it is possible but will require some modifications in source code for proper driver registration, which driver are you using, can you give me a few more details?

**Comment by CM4115** [comment]
Hello, thank you for your comment. I did manage to put jdbc db2 driver and its working. I just forgot to close this issue. Thank you once again.
