### ISSUE TITLE
SQL Server 2012+ requirement

### ISSUE THREAD

**Issue by mikefinger** [opensingular/singular-keycloak-database-federation#37]
Just wanted to ask if there was a specific vulnerability or issue with using SQL server versions before 2012?

We have a legacy database that we've not upgraded yet and might need to use this against that database.  JTDS seems to support SQL Server 2008R2, so just curious if there was a specific reason for 2012+ or was that all that was available for testing?

Thanks!

**Comment by viniciusuriel** [comment]
No specific reason, but the 2012 driver has some improvements in comparison to previous versions. There are no plans to support older versions. Feel free to fork this repo and change the driver version
