### ISSUE TITLE
Synchronization ignored as it's already in progress

### ISSUE THREAD

**Issue by FuX-STV** [opensingular/singular-keycloak-database-federation#42]
does anyone else have the problem with the message: Synchronization ignored as it's already in progress?

Keycloak version: 20.0.3

**Comment by FuX-STV** [comment]
problem fixed - wrong config

**Comment by fikrimuhaffizh** [comment]
hey can you tell me what's wrong with your config ? i have same issue. did we need to use same default column that filled in form to our database ?
